version: '2.4'

services:
  blynk_server:
    image: maxbanton/blynk-server
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9443:9443
    volumes:
     - /home/pi/docker/dbHomepi:/data/logs

  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
      - 5000:5000
    devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer, this requires pyserial
      - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/video0:/dev/video0
    volumes:
     - /home/pi/docker/dbHomepi:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    #environment:
    #  - ENABLE_MJPG_STREAMER=true
  
  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - GUID=0
  #    - TZ=America/Chicago
  #  volumes:
  #    - octoprint:/octoprint

#volumes:
#  docker_octoprint:
#  docker_blynk_server:

#  blynk_server:
#    image: maxbanton/blynk-server
#    restart: unless-stopped
#    ports:
#      - 8080:8080
#      - 9443:9443
#    volumes:
#     - blynk_server:/blynk_server
#volumes:
#  blynk_server:
